name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        rocketmq_version: ['4.9.2', '4.9.0']
    runs-on: ubuntu-20.04
    env:
      OPENRESTY_VER: 1.19.9.1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: download rocketmq
        run: |
          cd ~
          wget https://archive.apache.org/dist/rocketmq/${{matrix.rocketmq_version}}/rocketmq-all-${{matrix.rocketmq_version}}-bin-release.zip
          unzip rocketmq-all-${{matrix.rocketmq_version}}-bin-release.zip

      - name: run rocketmq
        run: |
          cd ~/rocketmq*/
          echo "traceTopicEnable=true" >> conf/dledger/broker-n0.conf
          echo "traceTopicEnable=true" >> conf/dledger/broker-n1.conf
          echo "traceTopicEnable=true" >> conf/dledger/broker-n2.conf
          bash bin/dledger/fast-try.sh start

      - name: download openresty
        run: |
          sudo apt-get -y install --no-install-recommends wget gnupg ca-certificates
          wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
          sudo apt-get update
          sudo apt-get -y install openresty

      - name: openresty version
        run: |
          sudo rm /usr/sbin/nginx
          sudo ln -s /usr/local/openresty/nginx/sbin/nginx /usr/sbin/nginx
          nginx -v

      - name: install test-nginx
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Test::Nginx

      - name: test
        run: |
          cd $GITHUB_WORKSPACE
          sudo prove -v t/*.t
